version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/app/src
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - api

#  ios:
#    build: /ios